export const majorArcana = [
  { name: 'The Fool', number: 0 },
  { name: 'The Magician', number: 1 },
  { name: 'The High Priestess', number: 2 },
  { name: 'The Empress', number: 3 },
  { name: 'The Emperor', number: 4 },
  { name: 'The Heirophant', number: 5 },
  { name: 'The Lovers', number: 6 },
  { name: 'The Chariot', number: 7 },
  { name: 'Strength', number: 8 },
  { name: 'The Hermit', number: 9 },
  { name: 'Wheel of Fortune', number: 10 },
  { name: 'Justice', number: 11 },
  { name: 'The Hanged Man', number: 12 },
  { name: 'Death', number: 13 },
  { name: 'Temperance', number: 14 },
  { name: 'The Devil', number: 15 },
  { name: 'The Tower', number: 16 },
  { name: 'The Star', number: 17 },
  { name: 'The Moon', number: 18 },
  { name: 'The Sun', number: 19 },
  { name: 'Judgement', number: 20 },
  { name: 'The World', number: 21 },
];

export const minorArcana = [
  { name: 'Ace of Wands', suit: 'Wands', number: 1 },
  { name: 'Two of Wands', suit: 'Wands', number: 2 },
  { name: 'Three of Wands', suit: 'Wands', number: 3 },
  { name: 'Four of Wands', suit: 'Wands', number: 4 },
  { name: 'Five of Wands', suit: 'Wands', number: 5 },
  { name: 'Six of Wands', suit: 'Wands', number: 6 },
  { name: 'Seven of Wands', suit: 'Wands', number: 7 },
  { name: 'Eight of Wands', suit: 'Wands', number: 8 },
  { name: 'Nine of Wands', suit: 'Wands', number: 9 },
  { name: 'Ten of Wands', suit: 'Wands', number: 10 },
  { name: 'Page of Wands', suit: 'Wands', number: 11 },
  { name: 'Knight of Wands', suit: 'Wands', number: 12 },
  { name: 'Queen of Wands', suit: 'Wands', number: 13 },
  { name: 'King of Wands', suit: 'Wands', number: 14 },
  { name: 'Ace of Cups', suit: 'Cups', number: 1 },
  { name: 'Two of Cups', suit: 'Cups', number: 2 },
  { name: 'Three of Cups', suit: 'Cups', number: 3 },
  { name: 'Four of Cups', suit: 'Cups', number: 4 },
  { name: 'Five of Cups', suit: 'Cups', number: 5 },
  { name: 'Six of Cups', suit: 'Cups', number: 6 },
  { name: 'Seven of Cups', suit: 'Cups', number: 7 },
  { name: 'Eight of Cups', suit: 'Cups', number: 8 },
  { name: 'Nine of Cups', suit: 'Cups', number: 9 },
  { name: 'Ten of Cups', suit: 'Cups', number: 10 },
  { name: 'Page of Cups', suit: 'Cups', number: 11 },
  { name: 'Knight of Cups', suit: 'Cups', number: 12 },
  { name: 'Queen of Cups', suit: 'Cups', number: 13 },
  { name: 'King of Cups', suit: 'Cups', number: 14 },
  { name: 'Ace of Swords', suit: 'Swords', number: 1 },
  { name: 'Two of Swords', suit: 'Swords', number: 2 },
  { name: 'Three of Swords', suit: 'Swords', number: 3 },
  { name: 'Four of Swords', suit: 'Swords', number: 4 },
  { name: 'Five of Swords', suit: 'Swords', number: 5 },
  { name: 'Six of Swords', suit: 'Swords', number: 6 },
  { name: 'Seven of Swords', suit: 'Swords', number: 7 },
  { name: 'Eight of Swords', suit: 'Swords', number: 8 },
  { name: 'Nine of Swords', suit: 'Swords', number: 9 },
  { name: 'Ten of Swords', suit: 'Swords', number: 10 },
  { name: 'Page of Swords', suit: 'Swords', number: 11 },
  { name: 'Knight of Swords', suit: 'Swords', number: 12 },
  { name: 'Queen of Swords', suit: 'Swords', number: 13 },
  { name: 'King of Swords', suit: 'Swords', number: 14 },
  { name: 'Ace of Pentacles', suit: 'Pentacles', number: 1 },
  { name: 'Two of Pentacles', suit: 'Pentacles', number: 2 },
  { name: 'Three of Pentacles', suit: 'Pentacles', number: 3 },
  { name: 'Four of Pentacles', suit: 'Pentacles', number: 4 },
  { name: 'Five of Pentacles', suit: 'Pentacles', number: 5 },
  { name: 'Six of Pentacles', suit: 'Pentacles', number: 6 },
  { name: 'Seven of Pentacles', suit: 'Pentacles', number: 7 },
  { name: 'Eight of Pentacles', suit: 'Pentacles', number: 8 },
  { name: 'Nine of Pentacles', suit: 'Pentacles', number: 9 },
  { name: 'Ten of Pentacles', suit: 'Pentacles', number: 10 },
  { name: 'Page of Pentacles', suit: 'Pentacles', number: 11 },
  { name: 'Knight of Pentacles', suit: 'Pentacles', number: 12 },
  { name: 'Queen of Pentacles', suit: 'Pentacles', number: 13 },
  { name: 'King of Pentacles', suit: 'Pentacles', number: 14 },
];

const tarot = [...majorArcana, ...minorArcana];

export default tarot;
